from fastapi import FastAPI, Depends, HTTPException, Header
from sqlalchemy.orm import Session
from sqlalchemy import text
from database import get_db
import models, schemas
import uuid

app = FastAPI()

# --- 1. ONBOARDING ENDPOINT ---
# The Frontend calls this to create a new company and get an API Key
@app.post("/api/onboarding", response_model=schemas.ProjectResponse)
def create_project(project_data: schemas.ProjectCreate, db: Session = Depends(get_db)):
    # Generate a simple API key (in real life, make this more secure)
    new_api_key = f"key-{uuid.uuid4().hex[:8]}"
    
    new_project = models.Project(
        name=project_data.name,
        description=project_data.description,
        api_key=new_api_key
    )
    db.add(new_project)
    db.commit()
    db.refresh(new_project)
    
    # In Phase 3, we will call the AI here to generate the SDK snippet.
    # For now, we return a placeholder.
    return {
        "project_id": str(new_project.id),
        "api_key": new_project.api_key,
        "sdk_snippet": f"// SDK for {project_data.name}\nimport {{ init }} from 'analytics';\ninit('{new_api_key}');"
    }

# --- 2. INGESTION ENDPOINT (The "Listen" Ear) ---
# The User's website calls this to send data
@app.post("/api/track")
def track_event(
    event_data: schemas.EventCreate, 
    x_api_key: str = Header(None), 
    db: Session = Depends(get_db)
):
    # Authenticate
    project = db.query(models.Project).filter(models.Project.api_key == x_api_key).first()
    if not project:
        raise HTTPException(status_code=401, detail="Invalid API Key")

    # Save to "Universal Bucket"
    new_event = models.Event(
        project_id=project.id,
        event_name=event_data.event_name,
        properties=event_data.properties
    )
    db.add(new_event)
    db.commit()
    return {"status": "success"}

# --- 3. DASHBOARD ENDPOINT (The "Speak" Mouth) ---
# The Frontend calls this to show charts
@app.get("/api/dashboard", response_model=schemas.DashboardResponse)
def get_dashboard(x_api_key: str = Header(None), db: Session = Depends(get_db)):
    # Authenticate
    project = db.query(models.Project).filter(models.Project.api_key == x_api_key).first()
    if not project:
        raise HTTPException(status_code=401, detail="Invalid API Key")

    # Fetch the "Playlist" of insights (generated by AI)
    configs = db.query(models.InsightConfig).filter(models.InsightConfig.project_id == project.id).all()
    
    widgets = []
    
    # Execute each SQL query safely
    for config in configs:
        try:
            result = db.execute(text(config.sql_query)).fetchall()
            
            # Format result for frontend (simplified for demo)
            # Assuming query returns: [Label, Value]
            formatted_data = [{"label": str(row[0]), "value": row[1]} for row in result]
            
            # If it's a single number (Stat Card), simplify structure
            if len(formatted_data) == 1 and config.insight_title.startswith("Total"):
                formatted_data = formatted_data[0]['value'] 

            widgets.append({
                "title": config.insight_title,
                "type": "bar_chart" if isinstance(formatted_data, list) else "stat_card",
                "data": formatted_data
            })
        except Exception as e:
            print(f"Query failed for {config.insight_title}: {e}")
            continue

    return {
        "company_name": project.name,
        "widgets": widgets
    }